package com.appointment.scheduler.service;

import com.appointment.scheduler.model.Appointment;
import com.appointment.scheduler.model.AppointmentStatus;
import com.appointment.scheduler.model.TimeSlot;
import com.appointment.scheduler.model.User;
import com.appointment.scheduler.observer.NotificationManager;
import com.appointment.scheduler.strategy.BookingRule;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import com.appointment.scheduler.model.AppointmentType;
/**
 * Service responsible for managing appointments.
 *
 * This class handles all core operations such as booking, cancellation,
 * modification, and reminders. It applies business rules using the
 * Strategy pattern and sends notifications using the Observer pattern.
 *
 * It acts as the main service layer connecting the domain logic
 * with application behavior.
 *
 * @author Fatima
 * @version 1.0
 */
public class AppointmentService {

    // List of all appointments in the system
    private final List<Appointment> appointments = new ArrayList<>();

    // List of rules applied during booking (Strategy Pattern)
    private final List<BookingRule> rules = new ArrayList<>();

    // Notification manager (Observer Pattern)
    private final NotificationManager notificationManager;

    // Stores the last error message for failed operations
    private String lastErrorMessage;

    /**
     * Default constructor initializes NotificationManager.
     */
    public AppointmentService() {
        this.notificationManager = new NotificationManager();
    }

    /**
     * Constructor with dependency injection for NotificationManager.
     *
     * @param notificationManager custom notification manager
     */
    public AppointmentService(NotificationManager notificationManager) {
        this.notificationManager = notificationManager;
    }

    /**
     * Adds a booking rule to be applied during booking.
     *
     * @param rule the booking rule
     */
    public void addRule(BookingRule rule) {
        rules.add(rule);
    }

    /**
     * Adds a new appointment to the system.
     *
     * @param appointment the appointment to add
     */
    public void addAppointment(Appointment appointment) {
        appointments.add(appointment);
    }

    /**
     * Retrieves all available appointments.
     *
     * @return list of available appointments
     */
    public List<Appointment> getAvailableAppointments() {
        List<Appointment> available = new ArrayList<>();

        for (Appointment appointment : appointments) {
            if (appointment.getStatus() == AppointmentStatus.AVAILABLE) {
                available.add(appointment);
            }
        }

        return available;
    }

    /**
     * Returns the last error message generated by a failed operation.
     *
     * @return error message or null if none
     */
    public String getLastErrorMessage() {
        return lastErrorMessage;
    }

    /**
     * Books an appointment if it is available and all rules are satisfied.
     *
     * @param appointmentId the appointment ID
     * @return true if booking is successful, false otherwise
     */
    public boolean bookAppointment(String appointmentId) {
        lastErrorMessage = null;

        for (Appointment appointment : appointments) {
            if (appointment.getId().equals(appointmentId)) {

                if (appointment.getStatus() != AppointmentStatus.AVAILABLE) {
                    lastErrorMessage = "Appointment is not available.";
                    return false;
                }

                for (BookingRule rule : rules) {
                    if (!rule.isValid(appointment)) {
                        lastErrorMessage = "Booking failed due to rule violation.";
                        return false;
                    }
                }

                appointment.setStatus(AppointmentStatus.CONFIRMED);

                notificationManager.notifyAllObservers(
                        appointment.getUser(),
                        buildBookingConfirmationMessage(appointment)
                );

                return true;
            }
        }

        lastErrorMessage = "Appointment not found.";
        return false;
    }

    /**
     * Cancels a confirmed future appointment.
     *
     * @param appointmentId the appointment ID
     * @return true if cancellation is successful, false otherwise
     */
    public boolean cancelAppointment(String appointmentId) {
        lastErrorMessage = null;

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        if (!isFutureAppointment(appointment)) {
            lastErrorMessage = "Only future appointments can be cancelled.";
            return false;
        }

        if (appointment.getStatus() != AppointmentStatus.CONFIRMED) {
            lastErrorMessage = "Only confirmed appointments can be cancelled.";
            return false;
        }

        appointment.setStatus(AppointmentStatus.AVAILABLE);

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                buildCancellationMessage(appointment)
        );

        return true;
    }

    /**
     * Modifies the time slot of a future appointment.
     *
     * @param appointmentId the appointment ID
     * @param newTimeSlot the new time slot
     * @return true if modification is successful, false otherwise
     */
    public boolean modifyAppointment(String appointmentId, TimeSlot newTimeSlot) {
        lastErrorMessage = null;

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        if (!isFutureAppointment(appointment)) {
            lastErrorMessage = "Only future appointments can be modified.";
            return false;
        }

        appointment.setTimeSlot(newTimeSlot);

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                buildModificationMessage(appointment)
        );

        return true;
    }

    /**
     * Allows an administrator to cancel any appointment.
     *
     * @param admin the admin user
     * @param appointmentId the appointment ID
     * @return true if operation is successful, false otherwise
     */
    public boolean adminCancelAppointment(User admin, String appointmentId) {
        lastErrorMessage = null;

        if (!isAdmin(admin)) {
            lastErrorMessage = "Only administrators can perform this action.";
            return false;
        }

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        appointment.setStatus(AppointmentStatus.AVAILABLE);

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                "Your appointment has been cancelled by the administrator."
        );

        return true;
    }

    /**
     * Allows an administrator to modify any appointment.
     *
     * @param admin the admin user
     * @param appointmentId the appointment ID
     * @param newTimeSlot the new time slot
     * @return true if operation is successful, false otherwise
     */
    public boolean adminModifyAppointment(User admin, String appointmentId, TimeSlot newTimeSlot) {
        lastErrorMessage = null;

        if (!isAdmin(admin)) {
            lastErrorMessage = "Only administrators can perform this action.";
            return false;
        }

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        appointment.setTimeSlot(newTimeSlot);

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                buildAdminModificationMessage(appointment)
        );

        return true;
    }

    /**
     * Sends a reminder notification for an upcoming appointment.
     *
     * @param appointmentId the appointment ID
     * @return true if reminder is sent successfully, false otherwise
     */
    public boolean sendReminder(String appointmentId) {
        lastErrorMessage = null;

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                buildReminderMessage(appointment)
        );

        return true;
    }

    public boolean adminSendCustomMessage(User admin, String appointmentId, String customMessage) {
        lastErrorMessage = null;

        if (!isAdmin(admin)) {
            lastErrorMessage = "Only administrators can perform this action.";
            return false;
        }

        if (customMessage == null || customMessage.trim().isEmpty()) {
            lastErrorMessage = "Message cannot be empty.";
            return false;
        }

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                customMessage
        );

        return true;
    }

    /**
     * Finds an appointment by its ID.
     */
    private Appointment findAppointmentById(String appointmentId) {
        for (Appointment appointment : appointments) {
            if (appointment.getId().equals(appointmentId)) {
                return appointment;
            }
        }
        return null;
    }

    /**
     * Checks if the appointment is in the future.
     */
    private boolean isFutureAppointment(Appointment appointment) {
        if (appointment.getTimeSlot() == null || appointment.getTimeSlot().getStartTime() == null) {
            return false;
        }
        return appointment.getTimeSlot().getStartTime().isAfter(LocalDateTime.now());
    }

    /**
     * Checks if a user is an administrator.
     */
    private boolean isAdmin(User user) {
        return user != null
                && user.getName() != null
                && user.getName().equalsIgnoreCase("admin");
    }

    private String buildBookingConfirmationMessage(Appointment appointment) {
        return "Dear " + appointment.getUser().getName()
                + ", your appointment has been confirmed for "
                + appointment.getTimeSlot().getStartTime() + ".";
    }

    private String buildCancellationMessage(Appointment appointment) {
        return "Dear " + appointment.getUser().getName()
                + ", your appointment scheduled for "
                + appointment.getTimeSlot().getStartTime()
                + " has been cancelled.";
    }

    private String buildModificationMessage(Appointment appointment) {
        return "Dear " + appointment.getUser().getName()
                + ", your appointment has been modified. New time: "
                + appointment.getTimeSlot().getStartTime() + ".";
    }

    private String buildAdminModificationMessage(Appointment appointment) {
        return "Dear " + appointment.getUser().getName()
                + ", your appointment has been modified by the administrator. New time: "
                + appointment.getTimeSlot().getStartTime() + ".";
    }

    private String buildReminderMessage(Appointment appointment) {
        return "Reminder: Dear " + appointment.getUser().getName()
                + ", you have an upcoming appointment at "
                + appointment.getTimeSlot().getStartTime() + ".";
    }
    
    
    
    
    //////////////////////////////////////////////
    
    /**
     * Retrieves all appointments in the system.
     *
     * @return list of all appointments
     */
    public List<Appointment> getAllAppointments() {
        return new ArrayList<>(appointments);
    }

    /**
     * Retrieves confirmed appointments for a specific user email.
     *
     * @param email user email
     * @return list of confirmed appointments for the user
     */
    public List<Appointment> getAppointmentsByUserEmail(String email) {
        List<Appointment> result = new ArrayList<>();

        if (email == null || email.trim().isEmpty()) {
            return result;
        }

        for (Appointment appointment : appointments) {
            if (appointment.getUser() != null
                    && appointment.getUser().getEmail() != null
                    && appointment.getUser().getEmail().equalsIgnoreCase(email.trim())
                    && appointment.getStatus() == AppointmentStatus.CONFIRMED) {
                result.add(appointment);
            }
        }

        return result;
    }

    /**
     * Books an available appointment slot for a real user.
     *
     * @param appointmentId selected appointment ID
     * @param user user who wants to book
     * @param type appointment type
     * @param participants number of participants
     * @return true if booking is successful
     */
    public boolean bookAppointment(String appointmentId, User user, AppointmentType type, int participants) {
        lastErrorMessage = null;

        Appointment appointment = findAppointmentById(appointmentId);

        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        if (appointment.getStatus() != AppointmentStatus.AVAILABLE) {
            lastErrorMessage = "Appointment is not available.";
            return false;
        }

        if (user == null || user.getName() == null || user.getName().trim().isEmpty()) {
            lastErrorMessage = "User name is required.";
            return false;
        }

        if (user.getEmail() == null || user.getEmail().trim().isEmpty()) {
            lastErrorMessage = "User email is required.";
            return false;
        }

        appointment.setUser(user);
        appointment.setType(type);
        appointment.setParticipants(participants);

        for (BookingRule rule : rules) {
            if (!rule.isValid(appointment)) {
                lastErrorMessage = "Booking failed due to rule violation.";
                return false;
            }
        }

        appointment.setStatus(AppointmentStatus.CONFIRMED);

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                buildBookingConfirmationMessage(appointment)
        );

        return true;
    }

    /**
     * Cancels a user's own future appointment.
     *
     * @param appointmentId appointment ID
     * @param email user email
     * @return true if cancellation is successful
     */
    public boolean cancelAppointmentByUser(String appointmentId, String email) {
        lastErrorMessage = null;

        Appointment appointment = findAppointmentById(appointmentId);

        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        if (!belongsToEmail(appointment, email)) {
            lastErrorMessage = "This appointment does not belong to this user.";
            return false;
        }

        return cancelAppointment(appointmentId);
    }

    /**
     * Moves a user's confirmed appointment to another available slot.
     *
     * @param appointmentId old confirmed appointment ID
     * @param newSlotId new available slot ID
     * @param email user email
     * @return true if rescheduling is successful
     */
    public boolean rescheduleAppointmentByUser(String appointmentId, String newSlotId, String email) {
        lastErrorMessage = null;

        Appointment oldAppointment = findAppointmentById(appointmentId);
        Appointment newAppointment = findAppointmentById(newSlotId);

        if (oldAppointment == null || newAppointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        if (!belongsToEmail(oldAppointment, email)) {
            lastErrorMessage = "This appointment does not belong to this user.";
            return false;
        }

        if (!isFutureAppointment(oldAppointment)) {
            lastErrorMessage = "Only future appointments can be modified.";
            return false;
        }

        if (newAppointment.getStatus() != AppointmentStatus.AVAILABLE) {
            lastErrorMessage = "The new slot is not available.";
            return false;
        }

        User user = oldAppointment.getUser();
        AppointmentType type = oldAppointment.getType();
        int participants = oldAppointment.getParticipants();

        newAppointment.setUser(user);
        newAppointment.setType(type);
        newAppointment.setParticipants(participants);

        for (BookingRule rule : rules) {
            if (!rule.isValid(newAppointment)) {
                lastErrorMessage = "New appointment violates booking rules.";
                return false;
            }
        }

        newAppointment.setStatus(AppointmentStatus.CONFIRMED);

        oldAppointment.setStatus(AppointmentStatus.AVAILABLE);
        oldAppointment.setUser(new User("0", "Available", "available@example.com"));
        oldAppointment.setParticipants(1);
        oldAppointment.setType(AppointmentType.INDIVIDUAL);

        notificationManager.notifyAllObservers(
                user,
                "Dear " + user.getName()
                        + ", your appointment has been moved to "
                        + newAppointment.getTimeSlot().getStartTime() + "."
        );

        return true;
    }

    /**
     * Allows administrator to move a reservation to an available slot.
     *
     * @param admin admin user
     * @param appointmentId old appointment ID
     * @param newSlotId new available slot ID
     * @return true if operation succeeds
     */
    public boolean adminRescheduleAppointment(User admin, String appointmentId, String newSlotId) {
        lastErrorMessage = null;

        if (!isAdmin(admin)) {
            lastErrorMessage = "Only administrators can perform this action.";
            return false;
        }

        Appointment oldAppointment = findAppointmentById(appointmentId);
        Appointment newAppointment = findAppointmentById(newSlotId);

        if (oldAppointment == null || newAppointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        if (oldAppointment.getStatus() != AppointmentStatus.CONFIRMED) {
            lastErrorMessage = "Only confirmed appointments can be moved.";
            return false;
        }

        if (newAppointment.getStatus() != AppointmentStatus.AVAILABLE) {
            lastErrorMessage = "The new slot is not available.";
            return false;
        }

        User user = oldAppointment.getUser();

        newAppointment.setUser(user);
        newAppointment.setType(oldAppointment.getType());
        newAppointment.setParticipants(oldAppointment.getParticipants());
        newAppointment.setStatus(AppointmentStatus.CONFIRMED);

        oldAppointment.setStatus(AppointmentStatus.AVAILABLE);
        oldAppointment.setUser(new User("0", "Available", "available@example.com"));
        oldAppointment.setParticipants(1);
        oldAppointment.setType(AppointmentType.INDIVIDUAL);

        notificationManager.notifyAllObservers(
                user,
                "Dear " + user.getName()
                        + ", your appointment has been moved by the administrator to "
                        + newAppointment.getTimeSlot().getStartTime() + "."
        );

        return true;
    }

    /**
     * Checks if an appointment belongs to a user email.
     *
     * @param appointment appointment
     * @param email user email
     * @return true if appointment belongs to this email
     */
    private boolean belongsToEmail(Appointment appointment, String email) {
        return appointment != null
                && appointment.getUser() != null
                && appointment.getUser().getEmail() != null
                && email != null
                && appointment.getUser().getEmail().equalsIgnoreCase(email.trim());
    }
}