package com.appointment.scheduler.service;

import com.appointment.scheduler.model.Appointment;
import com.appointment.scheduler.model.AppointmentStatus;
import com.appointment.scheduler.model.TimeSlot;
import com.appointment.scheduler.model.User;
import com.appointment.scheduler.observer.NotificationManager;
import com.appointment.scheduler.strategy.BookingRule;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Service responsible for managing appointments.
 *
 * This class handles all core operations such as booking, cancellation,
 * modification, and reminders. It applies business rules using the
 * Strategy pattern and sends notifications using the Observer pattern.
 *
 * It acts as the main service layer connecting the domain logic
 * with application behavior.
 *
 * @author Fatima
 * @version 1.0
 */
public class AppointmentService {

    // List of all appointments in the system
    private final List<Appointment> appointments = new ArrayList<>();

    // List of rules applied during booking (Strategy Pattern)
    private final List<BookingRule> rules = new ArrayList<>();

    // Notification manager (Observer Pattern)
    private final NotificationManager notificationManager;

    // Stores the last error message for failed operations
    private String lastErrorMessage;

    /**
     * Default constructor initializes NotificationManager.
     */
    public AppointmentService() {
        this.notificationManager = new NotificationManager();
    }

    /**
     * Constructor with dependency injection for NotificationManager.
     *
     * @param notificationManager custom notification manager
     */
    public AppointmentService(NotificationManager notificationManager) {
        this.notificationManager = notificationManager;
    }

    /**
     * Adds a booking rule to be applied during booking.
     *
     * @param rule the booking rule
     */
    public void addRule(BookingRule rule) {
        rules.add(rule);
    }

    /**
     * Adds a new appointment to the system.
     *
     * @param appointment the appointment to add
     */
    public void addAppointment(Appointment appointment) {
        appointments.add(appointment);
    }

    /**
     * Retrieves all available appointments.
     *
     * @return list of available appointments
     */
    public List<Appointment> getAvailableAppointments() {
        List<Appointment> available = new ArrayList<>();

        for (Appointment appointment : appointments) {
            if (appointment.getStatus() == AppointmentStatus.AVAILABLE) {
                available.add(appointment);
            }
        }

        return available;
    }

    /**
     * Returns the last error message generated by a failed operation.
     *
     * @return error message or null if none
     */
    public String getLastErrorMessage() {
        return lastErrorMessage;
    }

    /**
     * Books an appointment if it is available and all rules are satisfied.
     *
     * @param appointmentId the appointment ID
     * @return true if booking is successful, false otherwise
     */
    public boolean bookAppointment(String appointmentId) {
        lastErrorMessage = null;

        for (Appointment appointment : appointments) {
            if (appointment.getId().equals(appointmentId)) {

                if (appointment.getStatus() != AppointmentStatus.AVAILABLE) {
                    lastErrorMessage = "Appointment is not available.";
                    return false;
                }

                for (BookingRule rule : rules) {
                    if (!rule.isValid(appointment)) {
                        lastErrorMessage = "Booking failed due to rule violation.";
                        return false;
                    }
                }

                appointment.setStatus(AppointmentStatus.CONFIRMED);

                notificationManager.notifyAllObservers(
                        appointment.getUser(),
                        "Your appointment has been booked successfully!"
                );

                return true;
            }
        }

        lastErrorMessage = "Appointment not found.";
        return false;
    }

    /**
     * Cancels a confirmed future appointment.
     *
     * @param appointmentId the appointment ID
     * @return true if cancellation is successful, false otherwise
     */
    public boolean cancelAppointment(String appointmentId) {
        lastErrorMessage = null;

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        if (!isFutureAppointment(appointment)) {
            lastErrorMessage = "Only future appointments can be cancelled.";
            return false;
        }

        if (appointment.getStatus() != AppointmentStatus.CONFIRMED) {
            lastErrorMessage = "Only confirmed appointments can be cancelled.";
            return false;
        }

        appointment.setStatus(AppointmentStatus.AVAILABLE);

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                "Your appointment has been cancelled."
        );

        return true;
    }

    /**
     * Modifies the time slot of a future appointment.
     *
     * @param appointmentId the appointment ID
     * @param newTimeSlot the new time slot
     * @return true if modification is successful, false otherwise
     */
    public boolean modifyAppointment(String appointmentId, TimeSlot newTimeSlot) {
        lastErrorMessage = null;

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        if (!isFutureAppointment(appointment)) {
            lastErrorMessage = "Only future appointments can be modified.";
            return false;
        }

        appointment.setTimeSlot(newTimeSlot);

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                "Your appointment has been modified."
        );

        return true;
    }

    /**
     * Allows an administrator to cancel any appointment.
     *
     * @param admin the admin user
     * @param appointmentId the appointment ID
     * @return true if operation is successful, false otherwise
     */
    public boolean adminCancelAppointment(User admin, String appointmentId) {
        lastErrorMessage = null;

        if (!isAdmin(admin)) {
            lastErrorMessage = "Only administrators can perform this action.";
            return false;
        }

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        appointment.setStatus(AppointmentStatus.AVAILABLE);

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                "Your appointment has been cancelled by the administrator."
        );

        return true;
    }

    /**
     * Allows an administrator to modify any appointment.
     *
     * @param admin the admin user
     * @param appointmentId the appointment ID
     * @param newTimeSlot the new time slot
     * @return true if operation is successful, false otherwise
     */
    public boolean adminModifyAppointment(User admin, String appointmentId, TimeSlot newTimeSlot) {
        lastErrorMessage = null;

        if (!isAdmin(admin)) {
            lastErrorMessage = "Only administrators can perform this action.";
            return false;
        }

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        appointment.setTimeSlot(newTimeSlot);

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                "Your appointment has been modified by the administrator."
        );

        return true;
    }

    /**
     * Sends a reminder notification for an upcoming appointment.
     *
     * @param appointmentId the appointment ID
     * @return true if reminder is sent successfully, false otherwise
     */
    public boolean sendReminder(String appointmentId) {
        lastErrorMessage = null;

        Appointment appointment = findAppointmentById(appointmentId);
        if (appointment == null) {
            lastErrorMessage = "Appointment not found.";
            return false;
        }

        notificationManager.notifyAllObservers(
                appointment.getUser(),
                "Reminder: you have an upcoming appointment."
        );

        return true;
    }

    /**
     * Finds an appointment by its ID.
     */
    private Appointment findAppointmentById(String appointmentId) {
        for (Appointment appointment : appointments) {
            if (appointment.getId().equals(appointmentId)) {
                return appointment;
            }
        }
        return null;
    }

    /**
     * Checks if the appointment is in the future.
     */
    private boolean isFutureAppointment(Appointment appointment) {
        if (appointment.getTimeSlot() == null || appointment.getTimeSlot().getStartTime() == null) {
            return false;
        }
        return appointment.getTimeSlot().getStartTime().isAfter(LocalDateTime.now());
    }

    /**
     * Checks if a user is an administrator.
     */
    private boolean isAdmin(User user) {
        return user != null
                && user.getName() != null
                && user.getName().equalsIgnoreCase("admin");
    }
}